import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
GPIO.setup(7, GPIO.OUT)
GPIO.input(7)
GPIO.output(7, True)
GPIO.input(7)
GPIO.output(7, False)
GPIO.setup(11, GPIO.OUT)
GPIO.input(11)
GPIO.output(11, True)
GPIO.input(11)
GPIO.output(11, False)
